### ISSUE TITLE
AWS Lambda?

### ISSUE THREAD

**Issue by mtwalsh** [alex/letsencrypt-aws#11] opened 2016-01-20 22:36 UTC
It would be awesome to be able to run this using AWS Lambda, has anyone tried?  Is it possible?

**Comment by alex** [comment] 2016-01-20 22:37
I'd love to. Unfortunately doing external configuration with lambda doesn't appear practical ATM. Closing as a dupe of #6 :-)

**Closed as completed by alex** 2016-01-20 22:37 UTC

**Comment by mtwalsh** [comment] 2016-01-20 22:38
Thanks anyway, sorry for the dupe.

**Comment by alex** [comment] 2016-01-20 22:46
No worries. Hopefully once the config management is better (or someone
tells me the secret) we can add it!

On Wed, Jan 20, 2016 at 5:38 PM, Michael Walsh notifications@github.com
wrote:

> Thanks anyway, sorry for the dupe.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/11#issuecomment-173384838
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by aeirola** [comment] 2016-02-10 19:54
One possible solution would be to trigger the Lambda function with a periodically scheduled CloudWatch event containing static configuration data.

So something like:

![screen shot 2016-02-10 at 21 52 13](https://cloud.githubusercontent.com/assets/1143250/12959765/98f15d3e-d040-11e5-8783-214d07c00838.png)

Unfortunately I couldn't find any documentation about API access to creating the scheduled events, so configuration would have to be managed through the tiny input field in the rule configuration. This wouldn't be ideal, but doable.

**Comment by alex** [comment] 2016-02-10 19:55
If there's an API for this, and we can include a script to set it up, I'd
love to go this route. Without this level of automation I'm concerned that
it's too messy for people to use reliably.

On Wed, Feb 10, 2016 at 2:54 PM, Axel Eirola notifications@github.com
wrote:

> One possible solution would be to trigger the Lambda function with a
> periodically scheduled CloudWatch event containing static configuration
> data.
> 
> So something like:
> 
> [image: screen shot 2016-02-10 at 21 52 13]
> https://cloud.githubusercontent.com/assets/1143250/12959765/98f15d3e-d040-11e5-8783-214d07c00838.png
> 
> Unfortunately I couldn't find any documentation about API access to
> creating the scheduled events, so configuration would have to be managed
> through the tiny input field in the rule configuration. This wouldn't be
> ideal, but doable.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/11#issuecomment-182551519
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by aeirola** [comment] 2016-02-10 20:15
Digging deeper, there seems to be an API for controlling the rules.

[putRule](http://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutRule.html) creates a rule and defines the schedule for the event triggering, which should be followed by a call to [putTargets](http://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutTargets.html) which defines the function to be triggered, and the input data to be added to the event.

The rules and events are discussed more generally in the release blog post at https://aws.amazon.com/blogs/aws/new-cloudwatch-events-track-and-respond-to-changes-to-your-aws-resources/

**Comment by hayd** [comment] 2016-05-11 05:49
What is the issue with configuration?

Is it that lambda would need access to an aws_secret_access_key? If so, perhaps that could be kms en/decrypted... (edit: though that seems like a hack which a role would be better suited)

See https://github.com/Miserlou/Zappa for a lambda project setup purely from cli.

Edit: Or is it for the private key? In which case KMS is perfect! (You add it to the IAM.)
You can trigger aws lambda like a cron-like job.
